# Generated by Django 5.0.1 on 2024-01-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emsApp', '0003_alter_department_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='managers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emsApp.employee'),
        ),
    ]
